project:
  type: website
  output-dir: docs

website:
  title: "January Weiner"
  site-url: "https://january3.github.io"
  description: "Personal website of January Weiner"
  navbar:
    left:
      - bioinformatics.qmd
      - books.qmd
      - blog.qmd

format:
  html:
    theme: superhero
    css: styles.css
    toc: true



